<a href="https://colab.research.google.com/github/PunkPotatoQueen/Calculo-Numerico/blob/main/Matriz_de_Hilbert_em_Elimina%C3%A7%C3%A3o_Gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def matriz_de_Hilbert(n):

  A = np.zeros((n,n))

  B = n*[0]

  for i in range(0,n):
    for j in range(0,n):
      A[i][j] = 1 / ((i+1) + (j+1) -1)

  for i in range(0,n):
    s = 0
    for j in range(0,n):
      s = s + A[i][j]
    B[i] = s

  return A, B
# A é a matriz de Hilbert
# B é o vetor de termos independentes

def gauss (A, b):
  #A matriz dos coeficientes e b vetor de termos independente
  n = len(b)

  for k in range (0, n-1): #percorre diagonal
    pivo = A[k][k]

    for i in range (k+1,n): #percorre  linha
      m = A[i][k]/pivo

      for j in range (k,n): #percorre coluna
        A[i][j]= A[i][j] - m*A[k][j]

      b[i] = b[i]-m*b[k]
  return A,b

def subs_reversa (At,bt):
  n = len(bt)
  x = n*[0] #vetor solução
  x[n-1] = bt[n-1]/A[n-1][n-1]

  for k in range (n-2, -1, -1):#percorre as linhas de baixo para cima
    s = 0
    for j in range (k+1,n):
      s = s + A[k][j]*x[j]
    x[k] = (bt[k] -s) / A[k][k]
  return x #retorna a solução do SL A*x = b

A, B = matriz_de_Hilbert(3)
A_t, B_t = gauss(A, B)

print(A_t)
print(20*'__')
print(B_t)
print(20*'__')

x = subs_reversa(A_t, B_t)
print(x)

[[ 1.00000000e+00  5.00000000e-01  3.33333333e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03]]
________________________________________
[1.8333333333333333, 0.16666666666666663, 0.0055555555555554526]
________________________________________
[0.999999999999998, 1.0000000000000122, 0.9999999999999875]
